publishDir: '@breadchris'
baseURL: http://localhost:8000/@breadchris
title: Title
paginate: 5
theme:
    - papermod
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections:
    - posts
    - papermod
minify:
    disableXML: true
languages:
    en:
        languageName: English
        weight: 1
        taxonomies:
            category: categories
            series: series
            tag: tags
        menu:
            main:
                - name: Tags
                  url: tags/
                  weight: 10
outputs:
    home:
        - HTML
        - RSS
        - JSON
params:
    env: production
    description: description
    author: author
    defaultTheme: auto
    ShowShareButtons: false
    ShowReadingTime: false
    displayFullLangName: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    ShowRssButtonInSectionTermList: false
    ShowAllPagesInArchive: false
    ShowPageNums: false
    ShowToc: false
    images: []
    profileMode:
        enabled: false
        title: ""
        imageUrl: ""
        imageTitle: ""
        buttons: []
    homeInfoParams:
        Title: title
        Content: content
    socialIcons: []
    editPost:
        URL: ""
        Text: ""
        appendFilePath: false
    assets:
        disableHLJS: false
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
