baseURL: https://breadchris.com
languageCode: en-us
title: breadchris
theme: "PaperMod"

params:
  homeInfoParams:
    Title: Welcome, I hope you enjoy your stay! 
    Content: I have lots of ideas and not enough time to make them happen. I live to share and collaborate with others so please do not hesitate to reach out!

  socialIcons:
    - name: "github"
      url: "https://github.com/breadchris"
    - name: "twitter"
      url: "https://twitter.com/breadchris"
    - name: "twitch"
      url: "https://www.twitch.tv/marvelousbreadchris"
    - name: "rss"
      url: "https://breadchris.com/index.xml"
  ShowReadingTime: true
  author: "breadchris"
  contact: "contact@breadchris.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

  comments: true
  giscus:
    repo: "breadchris/notes"
    repoID: "R_kgDOHw5O7A"
    category: "Announcements"
    categoryID: "DIC_kwDOHw5O7M4CUSPv"
    mapping: "title"
    reactionsEnabled: "1"
    emitMetadata: "0"
    inputPosition: "top"
    theme: "preferred_color_scheme"
    lang: "en"
    loading: "lazy"

 #Google Analytics 4 optional
  env: #production
  GoogleAnalytics: "G-00000XXXXX" 
  sitemap:
    changefreq: daily
    filename: sitemap.xml
    priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
